version: '3.5'

services:
  social_api:
    build: ./
    ports:
      - 80:8000

    env_file:
      - ./.env
    
    command: >
      sh -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput --clear &&
        python manage.py runserver 0.0.0.0:8000
        "


    networks:
      - app-net
    volumes:
      - ./:/home/
      - static-vol:/home/static

    depends_on:
      - social_db

  social_db:
    image: postgres:latest
    networks:
      - app-net
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB:postgres
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
    env_file:
      - ./.env
      
  


networks:
  app-net:

volumes:
  postgres_data: {}
  static-vol: {}
